defaultTasks = {
    "#foodie": [
        "Eat a Chipotle burrito",
        "Go to the foodcarts at the top of Whitney",
        "Get Snacks at Elm City Market",
        "Eat a blank at Claire's Cornocopia ",
        "Eat Pepe's Pizza"
    ],
    "#productivity": [
        "5 min organization",
        "Write one page of an upcoming paper"
    ],
    "#dancemoves": [
        "The Sprinkler",
        "The Pop and Lock",
        "The Shopping Cart",
        "The John Travolta",
        "Thrusting",
        "Hammertime",
        "The MoonWalk",
        "Hoedown Throwdown",
        "The Nutbush",
        "Waving",
        "California Curls Dance",
        "Thriller",
        "The Worm",
        "Toprocking",
        "The Cabbage Patch",
        "Saturday Night Fever",
        "The Booty Slap",
        "The Nipple Rub",
        "The Drunk Man",
        "Slow Dancing",
        "The Window Wiper",
        "The Spongebob",
        "The Lawnmower",
        "The C-Walk",
        "The Swim",
        "The Oompa Loompa Dance",
        "The Hokie Pokie",
        "The Waltz",
        "The Chris Tucker",
        "The Passed Out",
        "The Beat it Dance",
        "The Can Can",
        "YMCA",
        "Soulja Boy",
        "The Macarena",
        "The Head Bounce",
        "The Chicken Dance",
        "The Chicken Wing",
        "The Twist",
        "Head Rolling",
        "Spirit Fingers",
        "The Shirt Helicopter",
        "Kung Fu Fighting",
        "The Skipping Dance",
        "The Hip Bounce",
        "Shuffling",
        "Bad Romance Dance",
        "Single Ladies Dance",
        "The Time Warp",
        "Gangman Style"
    ],
    "#day2dayhappiness": [
        "Learn  gratitude and list 5 good things about your day",
        "Write a thank you letter to someone that's done something nice for you",
        "Laugh for one minute straight with a buddy",
        "Deep breathing relaxation",
        "Do something unexpectedly nice for a friend",
        "15 minute meditation",
        "Reach out to an old friend",
        "Smile for 1 Minute",
        "Nod and smile at someone today",
        "Get 8 hours of sleep",
        "Send a High School Friend a birthday card in the mail",
        "Say thank you to someone to today",
        "Surprise a Coffee friend with Starbucks",
        "Surprise someone with a snack",
        "Say I forgive you to someone that wronged you",
        "Say I'm sorry to someone you wronged",
        "Say Please.",
        "Comfort someone and tell them everything is going to be OK",
        "Tell someone they're awesome",
        "Give a rando a high five",
        "Dance alone in a mirror",
        "Empower a friend to do something they're nervous about",
        "Ask someone about their dreams",
        "talk to someone new today",
        "get a number today"
    ],
    "#growth": [
        "Think of one win-win situation in your life",
        "Reach out to an acquaintance in your phonebook",
        "Make your bed today",
        "Read 25 minutes for pleasure",
        "Strengths/weaknesses",
        "Watch a ted talk a day for 30 days"
    ],
    "#drinking": [
        "Cards against humanity",
        "Flip cup",
        "Win a beer pong game",
        "Ice your friend",
        "Go to Woads",
        "Shotgun a beer",
        "Funnel a beer",
        "make nice drinks for a night",
        "take tequila and lime shots",
    ],
    "#entertainment": [
        "Watch Jaws",
        "Watch Cabin in the Woods",
        "Watch Scream"
    ],
    "#newhavenoutdoors": [
        "Float on the Maltby Lakes",
        "Visit Sperry Waterfall",
        "Hike east rock",
        "Visit the New Haven Lighthouse  ",
        "Abandoned theme park in milford"
    ],
    "#newhavenbars": [
        "Visit The Russian Lady",
        "Drink from the Mory's Cup",
        "Schedule a Tea Time at the Russian Lady",
        "Visit Bar Dance Party on a Thursday Night",
        "Visit Firehouse 12 for the Spring Jazz series",
        "Drink Scotch at Anna Liffey's ",
        "Get a drink at Cask Republic",
        "Raid Viva's with Friends",
        "Get a drink at Prime 16"
    ],
    "#studyspots": [
        "Do work at Blue State",
        "Do work at Panera",
        "Do work at B & N Cafe",
        "Do work at Sterling ",
        "Do work at Gheav",
        "Study at Sterling Library",
        "Study at Bass Library"
    ],
    "#travel": [
        "Visit Paris",
        "Visit London",
        "Smoke in Amsterdam",
        "Visit Fiji",
        "Visit New York City",
        "Visit Boston",
        "Go Surfing",
        "Go Skiing ",
        "Go to Mansion nightclub in Miami"
    ],
    "#yalebucketlist": [
        "Graduate Yale with a degree",
        "Swim in PWG's pool",
        "Compete in an IM Sport",
        "Play basketball at PWG",
        "Order a Wenzel",
        "Go to the Yale Observatory",
        "make a fine meal given dining hall ingredients",
        "Go to PWG Sauna",
        "Go to a Yale Naked Party",
        "Throw Frisbee in the courtyard"
    ],
    "#yalesports": [
        "Go to a Yale Hockey Game",
        "Go to a Track Meet at Coxe Cage",
        "Go to a Hockey Game at Ingalls Rink",
        "Go to a Yale Football Game",
        "Go to a Squash Match",
        "Wall st. pizza challenge"
    ],
    "#yaleculture": [
        "Visit Peabody",
        "Visit British Art Gallery",
        "Watch a sketch comedy group",
        "See the Wiffenpooffs perform",
        "Smoke Hooka at Mamoons"
    ]
}

imageAssociations = {'#yalebucketlist':'http://lorempixel.com/400/200/sports/1', 
					'#dancemoves':'http://lorempixel.com/400/200/sports/1', 
					'#growth':'http://lorempixel.com/400/200/sports/1', 
					'#yalesports':'http://lorempixel.com/400/200/sports/1', 
					'#newhavenbars':'http://lorempixel.com/400/200/sports/1', 
					'#newhavenoutdoors':'http://lorempixel.com/400/200/sports/1', 
					'#yaleculture':'http://lorempixel.com/400/200/sports/1', 
					'#drinking':'http://lorempixel.com/400/200/sports/1', 
					'#day2dayhappiness':'http://lorempixel.com/400/200/sports/1', 
					'#productivity':'http://lorempixel.com/400/200/sports/1', 
					'#travel':'http://lorempixel.com/400/200/sports/1', 
					'#entertainment':'http://lorempixel.com/400/200/sports/1', 
					'#studyspots':'http://lorempixel.com/400/200/sports/1', 
					'#foodie':'http://lorempixel.com/400/200/sports/1'}




